---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: '12.19.36'

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[ddnsupdate::default]
    attributes:
